name: gymnasium
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.1.4
  - matplotlib=3.7.1
  - scipy=1.13.1
  - scikit-learn=1.5.2
  - seaborn=0.13.1
  - tqdm=4.66.5
  - transformers=4.44.2
  - xgboost=2.1.1
  - pip
  - pip:
      - absl-py==1.4.0
      - accelerate==0.34.2
      - aiohttp==3.10.5
      - albumentations==1.4.15
      - jax==0.4.33
      - jaxlib==0.4.33
      - einops==0.8.0
      - opencv-contrib-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - fastai==2.7.17
      - fastcore==1.7.8
      - pyarrow==14.0.2
      - beautifulsoup4==4.12.3
      - folium==0.17.0
      - geemap==0.34.3
      - gdown==5.2.0
      - google-auth==2.27.0
      - google-cloud-storage==2.8.0
      - matplotlib-venn==1.1.1
      - pillow==10.4.0
      - requests==2.32.3
      - sentencepiece==0.2.0
      - rich==13.8.1
      - nbconvert==6.5.4
      - nbformat==5.10.4
      - jupyterlab_widgets==3.0.13
      - ipywidgets==7.7.1
      - plotly==5.24.1
      - scikit-image==0.24.0
      - statsmodels==0.14.3
      - altair==4.2.2
      - pandas-gbq==0.23.1
      - more-itertools==10.5.0
      - tqdm==4.66.5
      - moviepy==1.0.3
      - pyyaml==6.0.2
      - xarray==2024.9.0
      - sympy==1.13.3
      - protobuf==3.20.3
      - pillow==10.4.0
      - cloudpickle==2.2.1
      - gym==0.25.2
      - stable-baselines3==2.0.0a5
      - gymnasium==0.28.1
      - pandas-datareader==0.10.0
      - pyproj==3.6.1
      - geopandas==1.0.1
      - tqdm==4.66.5
      - folium==0.17.0
      - tensorflow-datasets==4.9.6
      - spacy==3.7.6
      - SQLAlchemy==2.0.35
      - tensorboard==2.17.0
      - wordcloud==1.9.3
      - yellowbrick==1.5
      - yfinance==0.2.43
      - huggingface-hub==0.24.7
      - huggingface_sb3==3.0
      - ale-py==0.10.0